name: Create pull request for sync note from dev_auto
on:
  push:
    branches:
      - dev_auto
jobs:
  SYNC_NOTE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: dev_auto

      - run: ls

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: publish note to blog
          title: sync note pull request
          body: sync note to blog
          branch: main
          base: dev_auto
          reviewers: AngusWG
